CREATE TABLE IF NOT EXISTS
Employee(
	EMPLOYEE_ID INT NOT NULL auto_increment,
	employee_lastname varchar(50),
	employee_firstname varchar(50),
	employee_phonenumber varchar(11),
    job_title varchar(100),

	PRIMARY KEY(EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS
Salesperson(
	SALESPERSON_ID INT NOT NULL auto_increment,
	EMPLOYEE_ID INT NOT NULL,

	PRIMARY KEY (SALESPERSON_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES Employee(EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS
Customer(
	CUSTOMER_ID INT NOT NULL auto_increment,
	lastname varchar(50),
	firstname varchar(50),
	phonenumber varchar(11),

	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS
Car(
	SERIAL_NUMBER INT NOT NULL auto_increment,
	CUSTOMER_ID INT,
	model_year YEAR,
	brand varchar(50),
	model varchar(50),
	variant varchar(50),
	transmission varchar(5),
	body_type varchar(50),
	fuel_type varchar(50),
	price DOUBLE,
    
	PRIMARY KEY (SERIAL_NUMBER),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS
Showroom_Car(
    SERIAL_NUMBER INT NOT NULL,
    CUSTOMER_ID INT,

	FOREIGN KEY(SERIAL_NUMBER) REFERENCES Car(SERIAL_NUMBER),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID)
);


CREATE TABLE IF NOT EXISTS
Invoice(
	INVOICE_ID INT NOT NULL auto_increment,
	EMPLOYEE_ID INT,
	CUSTOMER_ID INT,
	SERIAL_NUMBER INT,
	total_cost DOUBLE,
	date_issued DATE,

	PRIMARY KEY (INVOICE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES Employee(EMPLOYEE_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID),
	FOREIGN KEY (SERIAL_NUMBER) REFERENCES Car(SERIAL_NUMBER)
);

CREATE TABLE IF NOT EXISTS
Mechanic(
	MECHANIC_ID INT NOT NULL auto_increment,
	EMPLOYEE_ID INT NOT NULL,
	
	PRIMARY KEY(MECHANIC_ID),
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES Employee(EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS
Service(
	SERVICE_ID INT NOT NULL auto_increment,
	MECHANIC_ID INT,
	service_type varchar(100),

    PRIMARY KEY(SERVICE_ID),
    FOREIGN KEY(MECHANIC_ID) REFERENCES Mechanic(MECHANIC_ID)
);

CREATE TABLE IF NOT EXISTS
Maintenance(
	SERVICE_ID INT NOT NULL,
	maintenance_description varchar(100),

	FOREIGN KEY(SERVICE_ID) REFERENCES Service(SERVICE_ID)
);

CREATE TABLE IF NOT EXISTS
Part(
	PART_ID INT NOT NULL auto_increment,
	part_name varchar(100),
	price DOUBLE,

	PRIMARY KEY(PART_ID)
);

CREATE TABLE IF NOT EXISTS
Part_Replacement_Summary(
	SERVICE_ID INT NOT NULL,
	PART_ID INT,
	part_quantity INT,

	FOREIGN KEY(SERVICE_ID) REFERENCES Service(SERVICE_ID),
	FOREIGN KEY(PART_ID) REFERENCES Part(PART_ID)
);

CREATE TABLE IF NOT EXISTS
Service_History(
	SERVICE_HISTORY_ID INT NOT NULL auto_increment,
	SERVICE_ID INT,

	PRIMARY KEY(SERVICE_HISTORY_ID),
    FOREIGN KEY(SERVICE_ID) REFERENCES Service(SERVICE_ID)
);

CREATE TABLE IF NOT EXISTS
Customer_Car(
    SERIAL_NUMBER INT NOT NULL,
    CUSTOMER_ID INT,
    SERVICE_HISTORY_ID INT,

	FOREIGN KEY(SERIAL_NUMBER) REFERENCES Car(SERIAL_NUMBER),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID),
	FOREIGN KEY(SERVICE_HISTORY_ID) REFERENCES Service_History(SERVICE_HISTORY_ID)
);